name: Pull Request

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Copy CI gradle.properties
      run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

    - name: Set up our JDK environment
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Run Gradle build
      run: ./gradlew build

    - name: Run Android Lint
      uses: dvdandroid/action-android-lint@master
      with:
        github_token: ${{ secrets.TOKEN_GITHUB }}
        lint_xml_file: app/build/reports/lint-results.xml
        reporter: github-pr-check

    - name: Run Kotlin Linter
      uses: ScaCap/action-ktlint@master
      with:
        github_token: ${{ secrets.github_token }}
        android: true
        reporter: github-pr-check

    - name: Run detekt
      uses: DominuS-RU/Detekt-Action@v1.16.0
      with:
        github_token: ${{ secrets.github_token }}
        detekt_config: detekt-config.yml
        reviewdog_reporter: github-pr-check
